export const store = [
    // {
    //   id: 1,
    //   affSource: 0,
    //   affInfo:{
    //     StoreId: 'NA',
    //     Source: 'NA',
    //     SourceSite: 'NA',
    //     MarketPlaceCountry: 'IN',  
    //   },
    //   name: 'Amazon.in',
    //   slug: 'amazon',
    //   domainBrand: 'http://amazon.in/',
    //   storeLink: 'http://amazon.in/',
    //   dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
    // },
    // {
    //   id: 2,
    //   affSource: 0,
    //   affInfo:{
    //     StoreId: 'NA',
    //     Source: 'NA',
    //     SourceSite: 'NA',
    //     MarketPlaceCountry: 'IN',  
    //   },
    //   name: 'Flipkart',
    //   slug: 'flipkart',
    //   domainBrand: 'Flipkart.com',
    //   storeLink: 'https://www.myntra.com/',
    //   dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
    // },
    // {
    //   id: 3,     
    //   affSource: 1,
    //   affInfo:{
    //     StoreId: '123',
    //     Source: 'admitad',
    //     SourceSite: 'admitad.com',
    //     MarketPlaceCountry: 'IN',  
    //   },
    //   slug: 'myntra',
    //   name: 'myntra',
    //   domainBrand: 'Myntra.com',
    //   storeLink: 'https://www.myntra.com/',
    //   dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
    // },
    // {
    //   id: 4,
    //   affSource: 0,
    //   affInfo:{
    //     StoreId: '123',
    //     Source: 'admitad',
    //     SourceSite: 'admitad.com',
    //     MarketPlaceCountry: 'IN',  
    //   },
    //   name: 'Jabong',
    //   slug: 'jabong',
    //   domainBrand: 'Jabong.com',
    //   storeLink: 'https://www.Jabong.com/',
    //   dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
    // },
    {
      id: 5,
      affSource: 0,
      affInfo:{
        StoreId: '15542',
        Source: 'admitad',
        SourceSite: 'admitad.com',
        MarketPlaceCountry: 'IN',  
      },
      name: 'TataCliq',
      slug: 'tatacliq',
      domainBrand: 'tatacliq.com',
      storeLink: 'https://www.tatacliq.com/',
      dataUrl: 'https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&advcampaigns=15542&region=00&code=eyq48w62bj&user=vishwajit82&format=csv&v=4',
    },
    {
      id: 6,
      affSource: 0,
      affInfo:{
        StoreId: '13623',
        Source: 'admitad',
        SourceSite: 'admitad.com',
        MarketPlaceCountry: 'IN',  
      },
      name: 'Banggood',
      slug: 'banggood',
      domainBrand: 'banggood.com',
      storeLink: 'https://www.banggood.com/',
      dataUrl: 'https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=13623&user=vishwajit82&format=csv&v=4',
    },
    // {
    //     id: 7,
    //     affSource: 1,
    //     affInfo:{
    //       StoreId: '20675',
    //       Source: 'admitad',
    //       SourceSite: 'admitad.com',
    //       MarketPlaceCountry: 'IN',  
    //     },
    //     name: '2Gud',
    //     slug: '2gud',
    //     domainBrand: 'flipkart.com',
    //     storeLink: 'https://www.flipkart.com/',
    //     dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
    //   },
      // {
      //   id: 8,
      //   affSource: 1,
      //   affInfo:{
      //     StoreId: '20675',
      //     Source: 'admitad',
      //     SourceSite: 'admitad.com',
      //     MarketPlaceCountry: 'IN',  
      //   },
      //   name: 'paytm',
      //   slug: 'paytm',
      //   domainBrand: 'paytm.com',
      //   storeLink: 'https://www.paytm.com/',
      //   dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
      // },
      {
        id: 9,
        affSource: 1,
        affInfo:{
          StoreId: '18679',
          Source: 'admitad',
          SourceSite: 'admitad.com',
          MarketPlaceCountry: 'IN',  
        },
        name: 'PaytmMall',
        slug: 'paytmmall',
        domainBrand: 'paytmmall.com',
        storeLink: 'https://www.paytmmall.com/',
        dataUrl: 'https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=18679&user=vishwajit82&format=csv&v=4',
      },
      // {
      //   id: 10,
      //   affSource: 1,
      //   affInfo:{
      //     StoreId: '20675',
      //     Source: 'admitad',
      //     SourceSite: 'admitad.com',
      //     MarketPlaceCountry: 'IN',  
      //   },
      //   name: 'snapdeal',
      //   slug: 'snapdeal',
      //   domainBrand: 'snapdeal.com',
      //   storeLink: 'https://www.snapdeal.com/',
      //   dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
      // },
      // {
      //   id: 11,
      //   affSource: 1,
      //   affInfo:{
      //     StoreId: '20675',
      //     Source: 'admitad',
      //     SourceSite: 'admitad.com',
      //     MarketPlaceCountry: 'IN',  
      //   },
      //   name: 'Ajio',
      //   slug: 'ajio',
      //   domainBrand: 'ajio.com',
      //   storeLink: 'https://www.ajio.com/',
      //   dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
      // },
      {
        id: 12,
        affSource: 1,
        affInfo:{
          StoreId: '14291',
          Source: 'admitad',
          SourceSite: 'admitad.com',
          MarketPlaceCountry: 'IN',  
        },
        name: 'AliExpress',
        slug: 'aliexpress',
        domainBrand: 'aliexpress.com',
        storeLink: 'https://www.aliexpress.com/',
        dataUrl: 'https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=14291&user=vishwajit82&format=csv&v=4',
      },
      // {
      //   id: 13,
      //   affSource: 1,
      //   affInfo:{
      //     StoreId: '20675',
      //     Source: 'admitad',
      //     SourceSite: 'admitad.com',
      //     MarketPlaceCountry: 'IN',  
      //   },
      //   name: 'ShopClue',
      //   slug: 'shopclue',
      //   domainBrand: 'shopclue.com',
      //   storeLink: 'https://www.shopclue.com/',
      //   dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
      // },
      {
        id: 14,
        affSource: 1,
        affInfo:{
          StoreId: '21361',
          Source: 'admitad',
          SourceSite: 'admitad.com',
          MarketPlaceCountry: 'IN',  
        },
        name: 'Hostinger',
        slug: 'hostinger',
        domainBrand: 'hostinger.com',
        storeLink: 'https://www.hostinger.com/',
        dataUrl: 'https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=21361&user=vishwajit82&format=csv&v=4',
      },
      {
        id: 15,
        affSource: 1,
        affInfo:{
          StoreId: '14719',
          Source: 'admitad',
          SourceSite: 'admitad.com',
          MarketPlaceCountry: 'IN',  
        },
        name: 'FirstCry',
        slug: 'firstcry',
        domainBrand: 'firstcry.com',
        storeLink: 'https://www.firstcry.com/',
        dataUrl: 'https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=14719&user=vishwajit82&format=csv&v=4',
      },
      // {
      //   id: 16,
      //   affSource: 1,
      //   affInfo:{
      //     StoreId: '21122',
      //     Source: 'admitad',
      //     SourceSite: 'admitad.com',
      //     MarketPlaceCountry: 'IN',  
      //   },
      //   name: 'Envato',
      //   slug: 'envato',
      //   domainBrand: 'envato.com',
      //   storeLink: 'https://www.envato.com/',
      //   dataUrl: 'https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=21122&user=vishwajit82&format=csv&v=4',
      // },
      {
        id: 17,
        affSource: 1,
        affInfo:{
          StoreId: '22998',
          Source: 'admitad',
          SourceSite: 'admitad.com',
          MarketPlaceCountry: 'IN',  
        },
        name: 'Coursera',
        slug: 'coursera',
        domainBrand: 'coursera.com',
        storeLink: 'https://www.coursera.com/',
        dataUrl: 'https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=22998&user=vishwajit82&format=csv&v=4',
      },
      {
        id: 18,
        affSource: 1,
        affInfo:{
          StoreId: '20077',
          Source: 'admitad',
          SourceSite: 'admitad.com',
          MarketPlaceCountry: 'IN',  
        },
        name: 'Crocs',
        slug: 'crocs',
        domainBrand: 'crocs.com',
        storeLink: 'https://www.crocs.com/',
        dataUrl: 'https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=16245&advcampaigns=23433&advcampaigns=19858&advcampaigns=20077&user=vishwajit82&format=csv&v=4',
      },
      {
        id: 19,
        affSource: 1,
        affInfo:{
          StoreId: '22012',
          Source: 'admitad',
          SourceSite: 'admitad.com',
          MarketPlaceCountry: 'IN',  
        },
        name: 'Clarks',
        slug: 'clarks',
        domainBrand: 'clarks.com',
        storeLink: 'https://www.clarks.com/',
        dataUrl: 'https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=22012&user=vishwajit82&format=csv&v=4',
      },
      {
        id: 20,
        affSource: 1,
        affInfo:{
          StoreId: '23825',
          Source: 'admitad',
          SourceSite: 'admitad.com',
          MarketPlaceCountry: 'IN',  
        },
        name: 'BuyWow',
        slug: 'buywow',
        domainBrand: 'buywow.com',
        storeLink: 'https://www.buywow.com/',
        dataUrl: 'https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=23825&user=vishwajit82&format=csv&v=4',
      },
      {
        id: 21,
        affSource: 1,
        affInfo:{
          StoreId: '23825',
          Source: 'admitad',
          SourceSite: 'admitad.com',
          MarketPlaceCountry: 'IN',  
        },
        name: 'Boat',
        slug: 'boatlifestyle',
        domainBrand: 'boatlifestyle.com',
        storeLink: 'https://www.boatlifestyle.com/',
        dataUrl: 'https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=23961&user=vishwajit82&format=csv&v=4',
      },
      // {
      //   id: 21,
      //   affSource: 1,
      //   affInfo:{
      //     StoreId: '18363',
      //     Source: 'admitad',
      //     SourceSite: 'admitad.com',
      //     MarketPlaceCountry: 'IN',  
      //   },
      //   name: '360Security',
      //   slug: '360security',
      //   domainBrand: '360security.com',
      //   storeLink: 'https://www.360security.com/',
      //   dataUrl: 'https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=18363&user=vishwajit82&format=csv&v=4',
      // },
      
  ]