export const store = [
  // {
  //   id: 1,
  //   affSource: 0,
  //   affInfo:{
  //     StoreId: 'NA',
  //     Source: 'NA',
  //     SourceSite: 'NA',
  //     MarketPlaceCountry: 'IN',
  //   },
  //   name: 'Amazon.in',
  //   slug: 'amazon',
  //   domainBrand: 'http://amazon.in/',
  //   storeLink: 'http://amazon.in/',
  //   dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
  // },
  // {
  //   id: 2,
  //   affSource: 0,
  //   affInfo:{
  //     StoreId: 'NA',
  //     Source: 'NA',
  //     SourceSite: 'NA',
  //     MarketPlaceCountry: 'IN',
  //   },
  //   name: 'Flipkart',
  //   slug: 'flipkart',
  //   domainBrand: 'Flipkart.com',
  //   storeLink: 'https://www.myntra.com/',
  //   dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
  // },
  // {
  //   id: 3,
  //   affSource: 1,
  //   affInfo:{
  //     StoreId: '123',
  //     Source: 'admitad',
  //     SourceSite: 'admitad.com',
  //     MarketPlaceCountry: 'IN',
  //   },
  //   slug: 'myntra',
  //   name: 'myntra',
  //   domainBrand: 'Myntra.com',
  //   storeLink: 'https://www.myntra.com/',
  //   dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
  // },
  // {
  //   id: 4,
  //   affSource: 0,
  //   affInfo:{
  //     StoreId: '123',
  //     Source: 'admitad',
  //     SourceSite: 'admitad.com',
  //     MarketPlaceCountry: 'IN',
  //   },
  //   name: 'Jabong',
  //   slug: 'jabong',
  //   domainBrand: 'Jabong.com',
  //   storeLink: 'https://www.Jabong.com/',
  //   dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
  // },
  {
    id: 5,
    affSource: 0,
    affInfo: {
      StoreId: "15542",
      Source: "admitad",
      SourceSite: "admitad.com",
      MarketPlaceCountry: "IN",
    },
    name: "TataCliq",
    slug: "tatacliq-coupons",
    storeSlug: 'tatacliq',
    domainBrand: "tatacliq.com",
    storeLink: "https://www.tatacliq.com/",
    dataUrl:
      "https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&advcampaigns=15542&region=00&code=eyq48w62bj&user=vishwajit82&format=csv&v=4",
    metaInfo: {
      desc:
        "Tatacliq is an Online store which have Electronics & Lifestyle Products and they are committed to deliver to your door step. Sourced straight from the best brands and their authorised resellers from India and across the world, just for you. Begin your journey online with one of the fastest growing, e-commerce brands in the country and have a seamless online shopping experience. Immerse yourself in the joy of browsing through the best Indian and international brands in fashion, luxury, electronics and jewellery.",
    },
  },
  {
    id: 6,
    affSource: 0,
    affInfo: {
      StoreId: "13623",
      Source: "admitad",
      SourceSite: "admitad.com",
      MarketPlaceCountry: "IN",
    },
    name: "Banggood",
    slug: "banggood-coupons",
    storeSlug: 'banggood',
    domainBrand: "banggood.com",
    storeLink: "https://www.banggood.com/",
    dataUrl:
      "https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=13623&user=vishwajit82&format=csv&v=4",
    metaInfo: {
      desc:
        "Banggood was founded in 2004, specializing in computer software research and development. Focusing on foreign trade e-commerce. From there it developed into an online retailer for almost everything you need for happy living, eating and entertaining. We have 4 offices, one in Hong Kong, one in Shenzhen,one in Hangzhou, and one in Yiwu",
    },
  },
  // {
  //     id: 7,
  //     affSource: 1,
  //     affInfo:{
  //       StoreId: '20675',
  //       Source: 'admitad',
  //       SourceSite: 'admitad.com',
  //       MarketPlaceCountry: 'IN',
  //     },
  //     name: '2Gud',
  //     slug: '2gud',
  //     domainBrand: 'flipkart.com',
  //     storeLink: 'https://www.flipkart.com/',
  //     dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
  //   },
  // {
  //   id: 8,
  //   affSource: 1,
  //   affInfo:{
  //     StoreId: '20675',
  //     Source: 'admitad',
  //     SourceSite: 'admitad.com',
  //     MarketPlaceCountry: 'IN',
  //   },
  //   name: 'paytm',
  //   slug: 'paytm',
  //   domainBrand: 'paytm.com',
  //   storeLink: 'https://www.paytm.com/',
  //   dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
  // },
  // {
  //   id: 9,
  //   affSource: 1,
  //   affInfo:{
  //     StoreId: '18679',
  //     Source: 'admitad',
  //     SourceSite: 'admitad.com',
  //     MarketPlaceCountry: 'IN',
  //   },
  //   name: 'PaytmMall',
  //   slug: 'paytmmall',
  //   domainBrand: 'paytmmall.com',
  //   storeLink: 'https://www.paytmmall.com/',
  //   dataUrl: 'https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=18679&user=vishwajit82&format=csv&v=4',
  //   metaInfo: {
  //     desc : 'Paytm is India\'s largest mobile payments and commerce platform. It started with online mobile recharge and bill payments and has an online marketplace today. Paytm is the consumer brand of India\'s leading mobile internet company One97 Communications. One97\'s investors include SoftBank, SAIF Partners, Alibaba Group, Ant Financial (Alipay) and Mediatek.',
  //     }
  // },
  // {
  //   id: 10,
  //   affSource: 1,
  //   affInfo:{
  //     StoreId: '20675',
  //     Source: 'admitad',
  //     SourceSite: 'admitad.com',
  //     MarketPlaceCountry: 'IN',
  //   },
  //   name: 'snapdeal',
  //   slug: 'snapdeal',
  //   domainBrand: 'snapdeal.com',
  //   storeLink: 'https://www.snapdeal.com/',
  //   dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
  // },
  // {
  //   id: 11,
  //   affSource: 1,
  //   affInfo:{
  //     StoreId: '20675',
  //     Source: 'admitad',
  //     SourceSite: 'admitad.com',
  //     MarketPlaceCountry: 'IN',
  //   },
  //   name: 'Ajio',
  //   slug: 'ajio',
  //   domainBrand: 'ajio.com',
  //   storeLink: 'https://www.ajio.com/',
  //   dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
  // },
  {
    id: 12,
    affSource: 1,
    affInfo: {
      StoreId: "14291",
      Source: "admitad",
      SourceSite: "admitad.com",
      MarketPlaceCountry: "IN",
    },
    name: "AliExpress",
    slug: "aliexpress-coupons",
    storeSlug: 'aliexpress',
    domainBrand: "aliexpress.com",
    storeLink: "https://www.aliexpress.com/",
    dataUrl:
      "https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=14291&user=vishwajit82&format=csv&v=4",
    metaInfo: {
      desc:
        "Aliexpress is one of the biggest online marketplaces in the World, offering customers the lowest prices as well as the choice of more than 100 million products from 200,000 sellers, 20 most popular payment methods and shipping to more than 200 countries.",
    },
  },
  // {
  //   id: 13,
  //   affSource: 1,
  //   affInfo:{
  //     StoreId: '20675',
  //     Source: 'admitad',
  //     SourceSite: 'admitad.com',
  //     MarketPlaceCountry: 'IN',
  //   },
  //   name: 'ShopClue',
  //   slug: 'shopclue',
  //   domainBrand: 'shopclue.com',
  //   storeLink: 'https://www.shopclue.com/',
  //   dataUrl: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRxQ0ZxnljJ2YfJPqZlaIJfC80lxMAjwkb7D9A7eZoTNcGuhEpHwWoDlizlKD1Ro9R1R6FeB36OwjVs/pub?output=csv',
  // },
  {
    id: 14,
    affSource: 1,
    affInfo: {
      StoreId: "21361",
      Source: "admitad",
      SourceSite: "admitad.com",
      MarketPlaceCountry: "IN",
    },
    name: "Hostinger",
    slug: "hostinger-coupons",
    storeSlug: 'hostinger',
    domainBrand: "hostinger.com",
    storeLink: "https://www.hostinger.com/",
    dataUrl:
      "https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=21361&user=vishwajit82&format=csv&v=4",
    metaInfo: {
      desc:
        "Hostinger helps smart people to save a lot by providing exceptionally cheap web hosting with ultimate quality, premium web hosting features & fanatically dedicated live chat support. No matter where you are on your web building journey, you need to know that it’s possible to save smartly today! Here are only a few of the many features that make Hostinger a pioneer of affordable, premium & inexpensive web hosting.",
    },
  },
  {
    id: 15,
    affSource: 1,
    affInfo: {
      StoreId: "14719",
      Source: "admitad",
      SourceSite: "admitad.com",
      MarketPlaceCountry: "IN",
    },
    name: "FirstCry",
    slug: "firstcry",
    storeSlug: 'firstcry',
    domainBrand: "firstcry.com",
    storeLink: "https://www.firstcry.com/",
    dataUrl:
      "https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=14719&user=vishwajit82&format=csv&v=4",
    metaInfo: {
      desc:
        "Firstcry is the Asia's Largest Online Portal for Baby and Kids Products. The portal has over 90000+ items from the top brands like Mattel, Pigeon, Funskool, Hotwheels, Nuby, Pampers, Disney, Barbie, Gerber, Fisher Price, Mee Mee and many more.The company’s mission is to provide best of the products/brands at the lowest prices with great online shopping experience, free shipping and Prompt customer service.",
    },
  },
  // {
  //   id: 16,
  //   affSource: 1,
  //   affInfo:{
  //     StoreId: '21122',
  //     Source: 'admitad',
  //     SourceSite: 'admitad.com',
  //     MarketPlaceCountry: 'IN',
  //   },
  //   name: 'Envato',
  //   slug: 'envato',
  //   domainBrand: 'envato.com',
  //   storeLink: 'https://www.envato.com/',
  //   dataUrl: 'https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=21122&user=vishwajit82&format=csv&v=4',
  // },
  {
    id: 17,
    affSource: 1,
    affInfo: {
      StoreId: "22998",
      Source: "admitad",
      SourceSite: "admitad.com",
      MarketPlaceCountry: "IN",
    },
    name: "Coursera",
    slug: "coursera-coupons",
    storeSlug: 'coursera',
    domainBrand: "coursera.com",
    storeLink: "https://www.coursera.com/",
    dataUrl:
      "https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=22998&user=vishwajit82&format=csv&v=4",
    metaInfo: {
      desc:
        "Coursera provides online access to the world’s best education. More than 40 million learners from around the globe have come to Coursera to take courses offered by top universities like Yale, Stanford, Duke and top companies like Google and IBM.",
    },
  },
  {
    id: 18,
    affSource: 1,
    affInfo: {
      StoreId: "20077",
      Source: "admitad",
      SourceSite: "admitad.com",
      MarketPlaceCountry: "IN",
    },
    name: "Crocs",
    slug: "crocs-coupons",
    storeSlug: 'crocs',
    domainBrand: "crocs.com",
    storeLink: "https://www.crocs.com/",
    dataUrl:
      "https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=16245&advcampaigns=23433&advcampaigns=19858&advcampaigns=20077&user=vishwajit82&format=csv&v=4",
    metaInfo: {
      desc:
        "A world leader in innovative, casual footwear, Crocs, Inc. is dedicated to the future of comfort. Their original and most famous style, the Classic Clogs, are instantly recognized around the world, and for good reason: since 2002, they’ve sold more than 300 million pairs in over 90 countries!",
    },
  },
  {
    id: 19,
    affSource: 1,
    affInfo: {
      StoreId: "22012",
      Source: "admitad",
      SourceSite: "admitad.com",
      MarketPlaceCountry: "IN",
    },
    name: "Clarks",
    slug: "clarks-coupons",
    storeSlug: 'clarks',
    domainBrand: "clarks.com",
    storeLink: "https://www.clarks.com/",
    dataUrl:
      "https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=22012&user=vishwajit82&format=csv&v=4",
    metaInfo: {
      desc:
        " C. & J. Clark International Ltd, trading as Clarks, is a British-based, international shoe manufacturer and retailer. It was founded in 1825 by brothers Cyrus and James Clark in Street, Somerset, England – where it still has its headquarters. The company has over 1,000 branded stores and franchises around the world and also sells through third-party distribution.",
    },
  },
  {
    id: 20,
    affSource: 1,
    affInfo: {
      StoreId: "23825",
      Source: "admitad",
      SourceSite: "admitad.com",
      MarketPlaceCountry: "IN",
    },
    name: "BuyWow",
    slug: "buywow-coupons",
    storeSlug: 'buywow',
    domainBrand: "buywow.com",
    storeLink: "https://www.buywow.com/",
    dataUrl:
      "https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=23825&user=vishwajit82&format=csv&v=4",
    metaInfo: {
      desc:
        "Started in 2013, Based in Bangalore, India, BUY WOW are known and trusted for our premium quality products. The mammoth product portfolio includes supplements, herbal blends, creams, serums, lotions, shampoos, bath & body products, men’s grooming products, essential oils, massagers and more. However vast the range of products may be, it is unified by being pure, natural, health-friendly and easy-to-use for the everyday convenience of the modern urban life.WOW Skin Science is a nature-inspired beauty brand that has been committed to curating safe skin and hair care products for everyone to use. The products are free from sulphates, silicones, mineral oils, parabens, and artificial colors. The ingredients used are inspired by nature & dermatologically tested for your safety. Try today to fall in love with the complete range of Skin Care, Hair Care, and Bath & Body Products.",
    },
  },
  {
    id: 21,
    affSource: 1,
    affInfo: {
      StoreId: "23825",
      Source: "admitad",
      SourceSite: "admitad.com",
      MarketPlaceCountry: "IN",
    },
    name: "Boat",
    slug: "boatlifestyle-coupons",
    storeSlug: 'boatlifestyle',
    domainBrand: "boatlifestyle.com",
    storeLink: "https://www.boatlifestyle.com/",
    dataUrl:
      "https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=23961&user=vishwajit82&format=csv&v=4",
    metaInfo: {
      desc:
        "A lifestyle brand started in 2016 that deals with fashionable consumer electronics. The product range has expanded to include an extensive catalogue of headphones, earphones, speakers, travel chargers & premium cables. The brand has been gaining traction while riding the waves of Nirvana in the Audio Electronics sector. The average boAthead is prevalent across a number of categories. The “boAtheads” are the pillars upon which our foundation has been built. What makes a boAthead? That would be the trendsetters, a person that likes to make his/her presence known. The ones who love to rock out and have fun, to fearlessly dig deep and stay en-grained to their own truths. boAt’s distinct sound has brought known faces into our midst, showing that the love for good music is a universal one.",
    },
  },
  // {
  //   id: 21,
  //   affSource: 1,
  //   affInfo:{
  //     StoreId: '18363',
  //     Source: 'admitad',
  //     SourceSite: 'admitad.com',
  //     MarketPlaceCountry: 'IN',
  //   },
  //   name: '360Security',
  //   slug: '360security',
  //   domainBrand: '360security.com',
  //   storeLink: 'https://www.360security.com/',
  //   dataUrl: 'https://export.admitad.com/en/webmaster/websites/1777052/coupons/export/?website=1777052&code=eyq48w62bj&keyword=&language=&region=00&advcampaigns=18363&user=vishwajit82&format=csv&v=4',
  // },
];
