const cuelOffersRaw  = [
    {
      "Id": 85556,
      "Title": "Buy Tank Tops for Men starting from Rs.449",
      "slug": "get-flat-50-off-store",
      "Merchant": "Jockey",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.jockey.in/men/apparel-tops/tank-tops",
      "Status": "live",
      "Start_Date": "2021-05-05",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "05/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/2397/original/Jockey.png?1489668923",
      "Campaign_ID": 2397,
      "Campaign_Name": "Jockey"
    },
    {
      "Id": 85557,
      "Title": "Get Flat 50% off Store",
      "slug": "buy-innerwear-and-comfortwear-starting-from-rs360",
      "Merchant": "Jack & Jones",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.jackjones.in/upto-50-jj",
      "Status": "live",
      "Start_Date": "2021-05-05",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "05/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/3570/original/Jack___Jones.png?1579161240",
      "Campaign_ID": 3570,
      "Campaign_Name": "Jack & Jones"
    },
    {
      "Id": 85558,
      "Title": "Buy Innerwear and Comfortwear starting from Rs.360",
      "Merchant": "Jack & Jones",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.jackjones.in/jj-innerwear-and-comfortwear-62248",
      "Status": "live",
      "Start_Date": "2021-05-05",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "05/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/3570/original/Jack___Jones.png?1579161240",
      "Campaign_ID": 3570,
      "Campaign_Name": "Jack & Jones"
    },
    {
      "Id": 85610,
      "Title": "Get upto 40%-70% off on Women Western Wear",
      "Merchant": "Myntra",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.myntra.com/womenscomfortwearcollection2021?f=Gender%3Amen%20women%2Cwomen&plaEnabled=false&rf=Discount%20Range%3A40.0_100.0_40.0%20TO%20100.0",
      "Status": "live",
      "Start_Date": "2021-05-10",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "10/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/101/original/myntra.jpg?1613124982",
      "Campaign_ID": 101,
      "Campaign_Name": "Myntra"
    },
    {
      "Id": 85611,
      "Title": "Get min 50% off on Women Footwear",
      "Merchant": "Myntra",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.myntra.com/women-footwear?f=Categories%3AFlats%2CFlip%20Flops%2CHeels%2CSandals%3A%3AGender%3Amen%20women%2Cwomen&plaEnabled=false&rf=Discount%20Range%3A50.0_100.0_50.0%20TO%20100.0",
      "Status": "live",
      "Start_Date": "2021-05-10",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "10/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/101/original/myntra.jpg?1613124982",
      "Campaign_ID": 101,
      "Campaign_Name": "Myntra"
    },
    {
      "Id": 85642,
      "Title": "Latest Fashion Collection Starting 199",
      "Merchant": "Amazon India",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.amazon.in/b/ref=QAQuad11CTA_en_IN_3?pf_rd_r=9S19Y2WVDEHT1M53FQFX&pf_rd_p=a33f6185-47c9-4c05-a661-c5c211076a76&pf_rd_m=A1VBAL9TL5WCBF&pf_rd_s=merchandised-search-14&pf_rd_t=&pf_rd_i=6648217031&node=20847674031",
      "Status": "live",
      "Start_Date": "2021-05-14",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "14/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/817/original/Amazon.in__Online_Shopping_for_Books__Kindle_E_Readers__Kindle_accessories__E_Books_and_Movies___TV.png?1371175177",
      "Campaign_ID": 817,
      "Campaign_Name": "Amazon India"
    },
    {
      "Id": 85688,
      "Title": "Get min 80% off Store",
      "Merchant": "Ajio",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.ajio.com/s/min-80-percent-off-4320-51181",
      "Status": "live",
      "Start_Date": "2021-05-17",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "17/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/2589/original/Ajio.png?1516080211",
      "Campaign_ID": 2589,
      "Campaign_Name": "Ajio"
    },
    {
      "Id": 85689,
      "Title": "Get min 70% off Store",
      "Merchant": "Ajio",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.ajio.com/s/min-70-percent-off-4320-51181",
      "Status": "live",
      "Start_Date": "2021-05-17",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "17/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/2589/original/Ajio.png?1516080211",
      "Campaign_ID": 2589,
      "Campaign_Name": "Ajio"
    },
    {
      "Id": 85690,
      "Title": "Get min 60% off Store",
      "Merchant": "Ajio",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.ajio.com/s/min-60-percent-off-4320-51181",
      "Status": "live",
      "Start_Date": "2021-05-17",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "17/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/2589/original/Ajio.png?1516080211",
      "Campaign_ID": 2589,
      "Campaign_Name": "Ajio"
    },
    {
      "Id": 85749,
      "Title": "Buy Men Sportswear T-shirts Starting At Rs.299",
      "Merchant": "Tata Cliq",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.tatacliq.com/mens-clothing-sports-wear-t-shirts/c-msh1118100?q=:price-asc:category:MSH1118100",
      "Status": "live",
      "Start_Date": "2021-05-22",
      "End_Date": "2021-05-24",
      "Offer_Added_At": "22/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/2588/original/tata.png?1495706199",
      "Campaign_ID": 2588,
      "Campaign_Name": "Tata Cliq"
    },
    {
      "Id": 85752,
      "Title": "Get up to 50% off on Women Coats & Jackets",
      "Merchant": "Myntra",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.myntra.com/women-jackets-coats",
      "Status": "live",
      "Start_Date": "2021-05-22",
      "End_Date": "2021-05-24",
      "Offer_Added_At": "22/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/101/original/myntra.jpg?1613124982",
      "Campaign_ID": 101,
      "Campaign_Name": "Myntra"
    },
    {
      "Id": 85755,
      "Title": "Get up to 50% off on Women's Flip Flops & Slippers",
      "Merchant": "ShopClues",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.shopclues.com/womens-slippers-flip-flops.html",
      "Status": "live",
      "Start_Date": "2021-05-22",
      "End_Date": "2021-05-24",
      "Offer_Added_At": "22/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/152/original/Shopclues.png?1493899872",
      "Campaign_ID": 152,
      "Campaign_Name": "ShopClues"
    },
    {
      "Id": 85760,
      "Title": "Get up to 30% off on Baby Skin Care, Bath Accessories & Kids Grooming Products",
      "Merchant": "Firstcry",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.firstcry.com/searchresult?sale=3&brandid=0&searchstring=brand@~14@@@1@0@20@@@@@~172@@@@@@@@@@@&sort=popularity&ref2=menu_dd_bath-and-skin_massage-oils_H",
      "Status": "live",
      "Start_Date": "2021-05-22",
      "End_Date": "2021-05-24",
      "Offer_Added_At": "22/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/49/original/FC-Logo-big_store_tagline.png?1582718900",
      "Campaign_ID": 49,
      "Campaign_Name": "Firstcry"
    },
    {
      "Id": 85761,
      "Title": "Buy Kids Nightwear & Baby Night Suits Starting From At Rs.135",
      "Merchant": "Firstcry",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.firstcry.com/nightwear/6/165?scat=165&sort=bestseller&q=as_night&asid=43721#scat=165@@@@@@@@@@1@0@20@@@@@@@@@@&rating=&sort=PriceLowToHigh&&vi=three&pmonths=&cgen=&cat=6&skills=&measurement=&material=&Color=&Age=&gender=&ser=&premium=&deliverytype=&PageNo=1&scrollPos=0&pview=&tc=5033",
      "Status": "live",
      "Start_Date": "2021-05-22",
      "End_Date": "2021-05-24",
      "Offer_Added_At": "22/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/49/original/FC-Logo-big_store_tagline.png?1582718900",
      "Campaign_ID": 49,
      "Campaign_Name": "Firstcry"
    },
    {
      "Id": 85762,
      "Title": "Get up to 40% off on Women Gym Wear",
      "Merchant": "Zivame",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.zivame.com/activewear/training-gym.html?trksrc=navbar&trkid=l2",
      "Status": "live",
      "Start_Date": "2021-05-22",
      "End_Date": "2021-05-24",
      "Offer_Added_At": "22/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/146/original/zivame.png?1554962213",
      "Campaign_ID": 146,
      "Campaign_Name": "Zivame"
    },
    {
      "Id": 85763,
      "Title": "Get up to 30% off on Women Long Nightdress",
      "Merchant": "Zivame",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.zivame.com/sleepwear-nightwear/long-nightdress.html?trksrc=navbar&trkid=l2&page=3",
      "Status": "live",
      "Start_Date": "2021-05-22",
      "End_Date": "2021-05-24",
      "Offer_Added_At": "22/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/146/original/zivame.png?1554962213",
      "Campaign_ID": 146,
      "Campaign_Name": "Zivame"
    },
    {
      "Id": 85764,
      "Title": "Get up to 50% off on Women Ethnic Tops & Tunics",
      "Merchant": "BrandFactory",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.brandfactoryonline.com/fashion?type=list&sort=discount-high&filter_style_fq=185",
      "Status": "live",
      "Start_Date": "2021-05-22",
      "End_Date": "2021-05-24",
      "Offer_Added_At": "22/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/3881/original/BrandFactory.png?1567772670",
      "Campaign_ID": 3881,
      "Campaign_Name": "BrandFactory CPS"
    },
    {
      "Id": 85765,
      "Title": "Get up to 50% off on Men Casual Trousers",
      "Merchant": "BrandFactory",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.brandfactoryonline.com/fashion?type=list&sort=discount-high&filter_style_fq=177",
      "Status": "live",
      "Start_Date": "2021-05-22",
      "End_Date": "2021-05-24",
      "Offer_Added_At": "22/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/3881/original/BrandFactory.png?1567772670",
      "Campaign_ID": 3881,
      "Campaign_Name": "BrandFactory CPS"
    },
    {
      "Id": 85771,
      "Title": "Grab Flat 15% OFF on New Arrivals",
      "Merchant": "Lifestyle",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.lifestylestores.com/in/en/search?q=%3AallCategories%3Akids%3Abadge.title.en%3ANew&price=75,408&range=75,5500",
      "Status": "live",
      "Start_Date": "2021-05-24",
      "End_Date": "2021-05-25",
      "Offer_Added_At": "24/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/3094/original/Lifestyle.png?1492062644",
      "Campaign_ID": 3094,
      "Campaign_Name": "Lifestyle"
    },
    {
      "Id": 85772,
      "Title": "Grab Upto 50% OFF on Women Tees, Shorts & Loungewear Fashion Essentials Sale",
      "Merchant": "Lifestyle",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.lifestylestores.com/in/en/search?q=badge.invisible%3AAF07",
      "Status": "live",
      "Start_Date": "2021-05-24",
      "End_Date": "2021-05-24",
      "Offer_Added_At": "24/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/3094/original/Lifestyle.png?1492062644",
      "Campaign_ID": 3094,
      "Campaign_Name": "Lifestyle"
    },
    {
      "Id": 85773,
      "Title": "Grab Upto 50% OFF on Women Everyday Kurtas Fashion Essentials Sale",
      "Merchant": "Lifestyle",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.lifestylestores.com/in/en/c/women-ethnicwear-kurtasandkurtis?v=1",
      "Status": "live",
      "Start_Date": "2021-05-24",
      "End_Date": "2021-05-24",
      "Offer_Added_At": "24/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/3094/original/Lifestyle.png?1492062644",
      "Campaign_ID": 3094,
      "Campaign_Name": "Lifestyle"
    },
    {
      "Id": 85774,
      "Title": "Grab Upto 30% OFF on Beauty & Personal Care Essentials",
      "Merchant": "Lifestyle",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.lifestylestores.com/in/en/c/women-beauty",
      "Status": "live",
      "Start_Date": "2021-05-24",
      "End_Date": "2021-05-24",
      "Offer_Added_At": "24/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/3094/original/Lifestyle.png?1492062644",
      "Campaign_ID": 3094,
      "Campaign_Name": "Lifestyle"
    },
    {
      "Id": 85775,
      "Title": "Grab Polo T-Shirts Starting Rs.349",
      "Merchant": "LimeRoad",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.limeroad.com/men",
      "Status": "live",
      "Start_Date": "2021-05-24",
      "End_Date": "2021-05-25",
      "Offer_Added_At": "24/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/354/original/Limeroad.png?1513409313",
      "Campaign_ID": 354,
      "Campaign_Name": "LimeRoad"
    },
    {
      "Id": 85776,
      "Title": "Grab Upto 80% OFF on Office Shirts",
      "Merchant": "LimeRoad",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.limeroad.com/men",
      "Status": "live",
      "Start_Date": "2021-05-24",
      "End_Date": "2021-05-25",
      "Offer_Added_At": "24/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/354/original/Limeroad.png?1513409313",
      "Campaign_ID": 354,
      "Campaign_Name": "LimeRoad"
    },
    {
      "Id": 85777,
      "Title": "Grab Min 50% OFF on Round Neck Tees",
      "Merchant": "LimeRoad",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.limeroad.com/men",
      "Status": "live",
      "Start_Date": "2021-05-24",
      "End_Date": "2021-05-25",
      "Offer_Added_At": "24/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/354/original/Limeroad.png?1513409313",
      "Campaign_ID": 354,
      "Campaign_Name": "LimeRoad"
    },
    {
      "Id": 85778,
      "Title": "Grab Upto 40-80% OFF on Bermuda Shorts",
      "Merchant": "LimeRoad",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.limeroad.com/men",
      "Status": "live",
      "Start_Date": "2021-05-24",
      "End_Date": "2021-05-25",
      "Offer_Added_At": "24/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/354/original/Limeroad.png?1513409313",
      "Campaign_ID": 354,
      "Campaign_Name": "LimeRoad"
    },
    {
      "Id": 85785,
      "Title": "Get upto 40%-70% off Store",
      "Merchant": "Myntra",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.myntra.com/mast-and-harbour?plaEnabled=false&rf=Discount%20Range%3A40.0_100.0_40.0%20TO%20100.0",
      "Status": "live",
      "Start_Date": "2021-05-24",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "24/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/101/original/myntra.jpg?1613124982",
      "Campaign_ID": 101,
      "Campaign_Name": "Myntra"
    },
    {
      "Id": 85786,
      "Title": "Buy Sketchers starting from Rs.804",
      "Merchant": "Myntra",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.myntra.com/skechers?plaEnabled=false&sort=price_asc",
      "Status": "live",
      "Start_Date": "2021-05-24",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "24/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/101/original/myntra.jpg?1613124982",
      "Campaign_ID": 101,
      "Campaign_Name": "Myntra"
    },
    {
      "Id": 85787,
      "Title": "Buy Kurta Set for Women Under Rs.1199",
      "Merchant": "Myntra",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.myntra.com/women-kurtas-kurtis-suits?f=Categories%3AKurta%20Sets%2CKurtas&plaEnabled=false&rf=Price%3A239.0_1199.0_239.0%20TO%201199.0",
      "Status": "live",
      "Start_Date": "2021-05-24",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "24/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/101/original/myntra.jpg?1613124982",
      "Campaign_ID": 101,
      "Campaign_Name": "Myntra"
    },
    {
      "Id": 85524,
      "Title": "Get upto 70% off Store",
      "Merchant": "Ajio",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.ajio.com/s/2004-d-mhp-brands-explore-johnplayers-upto7",
      "Status": "live",
      "Start_Date": "2021-05-03",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "03/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/2589/original/Ajio.png?1516080211",
      "Campaign_ID": 2589,
      "Campaign_Name": "Ajio"
    },
    {
      "Id": 85525,
      "Title": "Get Flat 60% off Store",
      "Merchant": "Ajio",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.ajio.com/s/0804-d-mhp-brands-explore-trueblue-flat6",
      "Status": "live",
      "Start_Date": "2021-05-03",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "03/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/2589/original/Ajio.png?1516080211",
      "Campaign_ID": 2589,
      "Campaign_Name": "Ajio"
    },
    {
      "Id": 85526,
      "Title": "Starting from Rs.349 Store",
      "Merchant": "Ajio",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.ajio.com/s/0804-d-mhp-brands-explore-netplay-starting34",
      "Status": "live",
      "Start_Date": "2021-05-03",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "03/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/2589/original/Ajio.png?1516080211",
      "Campaign_ID": 2589,
      "Campaign_Name": "Ajio"
    },
    {
      "Id": 85527,
      "Title": "Under Rs.399 Store",
      "Merchant": "Pantaloons",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.pantaloons.com/c/collections-483?source=PT_D_H_FS_399&page=1&orderway=asc&orderby=popular&fp[]=Price__fq:0%20TO%20399",
      "Status": "live",
      "Start_Date": "2021-05-03",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "03/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/3941/original/Pantaloons.png?1577453778",
      "Campaign_ID": 3941,
      "Campaign_Name": "Pantaloons"
    },
    {
      "Id": 85528,
      "Title": "Under Rs.699 Store",
      "Merchant": "Pantaloons",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.pantaloons.com/c/collections-483?source=PT_D_H_FS_699&page=1&orderway=asc&orderby=popular&fp[]=Price__fq:0%20TO%20699",
      "Status": "live",
      "Start_Date": "2021-05-03",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "03/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/3941/original/Pantaloons.png?1577453778",
      "Campaign_ID": 3941,
      "Campaign_Name": "Pantaloons"
    },
    {
      "Id": 85531,
      "Title": "Everyday Kurtas for Women Under Rs.599",
      "Merchant": "Myntra",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.myntra.com/women-kurtas-kurtis-suits?f=Categories%3AKurtas%3A%3AFabric%3AChanderi%20Cotton%2CCotton%2CCotton%20Silk&plaEnabled=false&rf=Price%3A209.0_599.0_209.0%20TO%20599.0",
      "Status": "live",
      "Start_Date": "2021-05-03",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "03/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/101/original/myntra.jpg?1613124982",
      "Campaign_ID": 101,
      "Campaign_Name": "Myntra"
    },
    {
      "Id": 85532,
      "Title": "Buy Mens Innerwear starting from Rs.149",
      "Merchant": "Myntra",
      "Categories": "Fashion",
      "Description": "",
      "Terms": "",
      "Coupon_Code": "",
      "URL": "https://linksredirect.com/?pub_id=116382&url=https://www.myntra.com/men-innerwear?f=Categories%3ABoxers%2CBriefs%2CInnerwear%20Vests%2CTrunk&plaEnabled=false",
      "Status": "live",
      "Start_Date": "2021-05-03",
      "End_Date": "2021-05-31",
      "Offer_Added_At": "03/05/2021",
      "Image_URL": "https://cdn0.cuelinks.com/campaigns/101/original/myntra.jpg?1613124982",
      "Campaign_ID": 101,
      "Campaign_Name": "Myntra"
    }
  ]
  var cuelOffers = [];
  for (var i = 0; i < cuelOffersRaw.length; i++ ) {
   
    if(cuelOffersRaw[i]){
        cuelOffers[i] = {};
        cuelOffers[i]['title'] = cuelOffersRaw[i].Title;
        cuelOffers[i]['merchant'] = cuelOffersRaw[i].Merchant;
        cuelOffers[i]['id'] = cuelOffersRaw[i].Id;
        cuelOffers[i]['categories'] = cuelOffersRaw[i].Categories;
        cuelOffers[i]['description'] = cuelOffersRaw[i].Description;
        cuelOffers[i]['coupon_code'] = cuelOffersRaw[i].Coupon_Code;
        cuelOffers[i]['url'] = cuelOffersRaw[i].URL;
        cuelOffers[i]['start_date'] = cuelOffersRaw[i].Start_Date;
        cuelOffers[i]['end_date'] = cuelOffersRaw[i].End_Date;
        cuelOffers[i]['offer_added_at'] = cuelOffersRaw[i].Offer_Added_At;
        cuelOffers[i]['image_url'] = cuelOffersRaw[i].Image_URL;
        cuelOffers[i]['campaign_name'] = cuelOffersRaw[i].Campaign_Name;
    }  
  };

  module.exports = cuelOffers
